name: pytest-1-checkout
on: workflow_dispatch

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: pre - checkout
        run: |
          pwd
          ls -lh
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: "yongyuca/pytestdemo"
          ref: main
      - name: after checkout
        run: |
          pwd
          ls -lh
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
