name: pytest
on: workflow_dispatch

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        run: |
          git clone https://github.com/yongyuca/pytestdemo.git
          cd pytestdemo
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
